module.exports = {
    apps : [
        {
            name : "[CATAPULT] Queue Worker",
            script: "artisan",
            args: ["queue:work", "--tries=5"],
            exec_interpreter: "php",
            exec_mode : "fork",
            max_memory_restart : "1G",
            watch: false,
            merge_logs: true,
            autorestart: true,
        },
        {
            name : "[CATAPULT][CDIS] FDFS",
            script: "artisan",
            args: ["cdis:fetch-data-for-sync"],
            exec_interpreter: "php",
            exec_mode : "fork",
            max_memory_restart : "1G",
            watch: false,
            merge_logs: true,
            autorestart: true,
        },
        {
            name : "[CATAPULT][CDIS] CDTF",
            script: "artisan",
            args: ["cdis:convert-data-to-file"],
            exec_interpreter: "php",
            exec_mode : "fork",
            max_memory_restart : "1G",
            watch: false,
            merge_logs: true,
            autorestart: true,
        },
        {
            name : "[CATAPULT][POS] SDF",
            script: "artisan",
            args: ["pos:sync-data-file"],
            exec_interpreter: "php",
            exec_mode : "fork",
            max_memory_restart : "1G",
            watch: false,
            merge_logs: true,
            autorestart: true,
        },
        {
            name : "[CATAPULT][POS] CDF",
            script: "artisan",
            args: ["pos:convert-data-file"],
            exec_interpreter: "php",
            exec_mode : "fork",
            max_memory_restart : "1G",
            watch: false,
            merge_logs: true,
            autorestart: true,
        },
        {
            name : "[CATAPULT][POS] SDFCF",
            script: "artisan",
            args: ["pos:send-data-from-converted-file"],
            exec_interpreter: "php",
            exec_mode : "fork",
            max_memory_restart : "1G",
            watch: false,
            merge_logs: true,
            autorestart: true,
        },
    ]
}
