module.exports = {
    apps : [
        {
            name : "CPLT-Queue Worker",
            script: "artisan",
            args: ["queue:work", "--tries=5"],
            exec_interpreter: "php",
            exec_mode : "fork",
            max_memory_restart : "5G",
            watch: false,
            merge_logs: true,
            autorestart: true,
        },
        // {
        //     name : "CPLT-CDIS-FDFS",
        //     script: "artisan",
        //     args: ["cdis:fetch-data-for-sync"],
        //     exec_interpreter: "php",
        //     exec_mode : "fork",
        //     max_memory_restart : "5G",
        //     watch: false,
        //     merge_logs: true,
        //     autorestart: true,
        // },
        // {
        //     name : "CPLT-CDIS-CDTF",
        //     script: "artisan",
        //     args: ["cdis:convert-data-to-file"],
        //     exec_interpreter: "php",
        //     exec_mode : "fork",
        //     max_memory_restart : "5G",
        //     watch: false,
        //     merge_logs: true,
        //     autorestart: true,
        // },
        {
            name : "CPLT-POS-SDF",
            script: "artisan",
            args: ["pos:sync-data-file"],
            exec_interpreter: "php",
            exec_mode : "fork",
            max_memory_restart : "5G",
            watch: false,
            merge_logs: true,
            autorestart: true,
        },
        {
            name : "CPLT-POS-CDF",
            script: "artisan",
            args: ["pos:convert-data-file"],
            exec_interpreter: "php",
            exec_mode : "fork",
            max_memory_restart : "5G",
            watch: false,
            merge_logs: true,
            autorestart: true,
        },
        {
            name : "CPLT-POS-SDFCF",
            script: "artisan",
            args: ["pos:send-data-from-converted-file"],
            exec_interpreter: "php",
            exec_mode : "fork",
            max_memory_restart : "5G",
            watch: false,
            merge_logs: true,
            autorestart: true,
        },
    ]
}
