<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

class AlterTerminalTransactionTable extends Migration
{
    protected $tableName = 'cdis_terminal_transaction';
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::table($this->tableName, function (Blueprint $table) {
            if (Schema::hasColumn($this->tableName, 'transaction_id')) {
                $table->string('transaction_id', 64)->default('0')->change();
            }
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::table($this->tableName, function (Blueprint $table) {
            if (Schema::hasColumn($this->tableName, 'transaction_id')) {
                // $table->bigInteger('transaction_id')->default(0)->change();

                // Huh? Invalid SQL generated by Laravel during the down() migration, 
                // specifically because you are trying to change a column to BIGINT but still 
                // applying CHARACTER SET and COLLATE options — which are only valid for
                // string/text columns, not numeric types like BIGINT. (I think we need to upgrade version!)

                // Use raw SQL to avoid charset/collation errors on BIGINT
                DB::statement("ALTER TABLE `{$this->tableName}` CHANGE `transaction_id` `transaction_id` BIGINT NOT NULL DEFAULT 0");
            }
        });
    }
}
