<?php

namespace App\Console\Commands\POSToCDIS;

use App\Entities\FileStorageSetup;
use App\Enums\CommonErrors;
use App\Enums\ReportFileType;
use App\Enums\Status;
use App\Enums\StorageType;
use App\Helpers\CustomPinger as Ping;
use App\Repositories\Contracts\FileStorageSetupRepository;
use App\Repositories\Contracts\TerminalFileSetupRepository;
use App\Services\ErrorLogService;
use App\Traits\FileStorageSetupTrait;
use App\Traits\GenericHelper;
use App\Traits\OutputBufferTrait;
use App\Traits\StorageTrait;
use App\Traits\TerminalFileSetupTrait;
use GuzzleHttp\Client;
use GuzzleHttp\Psr7\Response as Psr7Response;
use Illuminate\Console\Command;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Http\Response;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\Response as FacadesResponse;
use Illuminate\Support\Facades\Storage;

class FileTransfer extends Command implements ShouldQueue
{
    use GenericHelper, OutputBufferTrait, StorageTrait, TerminalFileSetupTrait, FileStorageSetupTrait;

    public $errorLogService;

    /**
     * The time delay interval in copying file to next file 
     *
     * @var int
     */
    private $timeDelay = 3;

    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'pos:transfer {--type=0}';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Automatically transfer report file from POS directory to defined Catapult directory';

    /**
     * Create a new command instance.
     *
     * @param ErrorLogService  $errorLogService
     * @return void
     */
    public function __construct(ErrorLogService $errorLogService)
    {
        parent::__construct();

        $this->errorLogService = $errorLogService;
    }

    /**
     * Execute the console command.
     *
     * @return mixed
     */
    public function handle()
    {
        $type = $this->option('type') ?: null;
        $filters =(object) ['status' => Status::ACTIVE];
        if (! empty($type)) {
            $filters->type = $type;

            $typeDescription = ReportFileType::getDescription(intval($type));
            $this->line(__('info.uploading_report')." [$typeDescription]");
        }
        while (true) {

            $terminalFileSetups = app()->make(TerminalFileSetupRepository::class)->list($filters);
            if (count($terminalFileSetups) > 0) {
                foreach ($terminalFileSetups as $terminalFile) {

                    $terminalPath = $terminalFile->terminal_path;

                    $sourceDirectory = '/';

                    // If sub-directory is configured then we need to
                    // extract the content to get the folder name
                    $subFolder =  $this->getSubFolder($terminalFile);
                    if ($subFolder) {
                        $terminalPath = "$terminalFile->terminal_path/$subFolder";
                    }

                    // initialize the target disk that handles destination
                    $targetTransferDisk = $this->getLocalStorageDisk($terminalFile);
                    if (! $targetTransferDisk) {
                        $this->setErrorLog(__('error.no_file_storage_setup_detected'));
                        continue;
                    }

                    // initialize target root directory by terminal name, then create if not exist
                    $targetTransferRootTerminal = '/Reports/'.cleanNonAlphaNumericChars($terminalFile->name);
                    $this->createDirectoryIfNotExist($targetTransferDisk, $targetTransferRootTerminal);

                    // initialize source disk, that contains all files generated by POS System
                    $storageDisk = $this->resolveFilesystemDisk(cleanNonAlphaNumericChars(strtolower($terminalFile->name)), $terminalPath);                  
                    $files = $storageDisk->allFiles($sourceDirectory);

                    if (count($files)) {
                        $this->createLog(__('info.files_found_in', ['value' => $terminalPath]), 'info', true,[$terminalFile->name, count($files) ]);

                        foreach ($files as $file) {
                            $targetFilename = "$targetTransferRootTerminal/$file";

                            // Check if file already exist in destination folder
                            if ($targetTransferDisk->exists($targetFilename)) {
                                // It means file is already been copied, so we need
                                // to ignore this and proceed to next file
                                $this->createLog($targetFilename, 'info', true, ['Transfered']);
                                continue;
                            } else {
                                try {
                                    // To avoid FatalErrorException due to allocated memory size limit,
                                    // we set memory limit before reading the content of the file
                                    ini_set('memory_limit', '-1');
                                    $fileContent = $storageDisk->get($file);
                                    $targetTransferDisk->put($targetFilename, $fileContent);
                                    
                                    $this->createLog("$file : $terminalPath ---> $targetTransferRootTerminal", 'line', true, ['Moving']);
                                } catch (\Exception $e) {
                                    $this->createLog(json_encode($e), 'error', true, ['FileException']);
                                    continue;
                                }
                            }
                            sleep($this->timeDelay); // add time delay to avoid too many request
                        }
                    } else {
                        $this->createLog(__('info.no_files_found_in', ['value' => $terminalPath]), 'warn', true, [$terminalFile->name]);
                    }
                }
            } else {
                $this->createLog(__('error.no_terminal_file_setup_detected'), 'warn', true,);
            }

            $this->flushOutputBuffer();
            sleep($this->timeDelay); 
        }
    }

    private function setErrorLog($message, $status = [])
    {
        $this->createLog($message, 'error', true, $status);
        $this->flushOutputBuffer();

        sleep(5);
    }
}
