<?php

use App\Entities\FieldMappingPreset;
use Eighty8\LaravelSeeder\Migration\MigratableSeeder;
use Eighty8\LaravelSeeder\Repository\DisableForeignKeysTrait;

class CdisTransactionFields extends MigratableSeeder
{
    use DisableForeignKeysTrait;

    /**
     * Run the database seeder.
     */
    public function run(): void
    {
        $transaction = [
            'type' => '2',
            'preset_name' => 'Transaction (Default)',
            'data_entry' => 'transaction',
            'status' => 1,
            'created_by' => 1,
        ];

        $fieldMappingPreset = FieldMappingPreset::create($transaction);

        $fieldMappingPresetDetail = [
            // < ** TRANSACTION HEAD ** > //
            [
                'required' => 1,
                'field' => 'transaction_id',
                'description' => null,
                'mapping_type' => 'INT',
                'file_name' => 'TH',
                'column_name' => 'transaction_id',
            ],
            [
                'required' => 1,
                'field' => 'branch_code',
                'description' => null,
                'mapping_type' => 'VARCHAR',
                'file_name' => 'TH',
                'column_name' => 'branch_code',
            ],
            [
                'required' => 1,
                'field' => 'terminal_number',
                'description' => null,
                'mapping_type' => 'VARCHAR',
                'file_name' => 'TH',
                'column_name' => 'terminal_number',
            ],
            [
                'required' => 1,
                'field' => 'date',
                'description' => null,
                'mapping_type' => 'DATETIME',
                'file_name' => 'TH',
                'column_name' => 'date',
            ],
            [
                'required' => 1,
                'field' => 'amount',
                'description' => null,
                'mapping_type' => 'DECIMAL',
                'file_name' => 'TH',
                'column_name' => 'amount',
            ],
            [
                'required' => 1,
                'field' => 'transaction_type',
                'description' => null,
                'mapping_type' => 'INT',
                'file_name' => 'TH',
                'column_name' => 'transaction_type',
            ],
            [
                'required' => 1,
                'field' => 'is_zread',
                'description' => null,
                'mapping_type' => 'INT',
                'file_name' => 'TH',
                'column_name' => 'is_zread',
            ],
            [
                'required' => 1,
                'field' => 'status',
                'description' => null,
                'mapping_type' => 'INT',
                'file_name' => 'TH',
                'column_name' => 'status',
            ],
            [
                'required' => 1,
                'field' => 'type',
                'description' => null,
                'mapping_type' => 'INT',
                'file_name' => 'TH',
                'column_name' => 'type',
            ],
            [

                'required' => 1,
                'field' => 'gross',
                'description' => null,
                'mapping_type' => 'DECIMAL',
                'file_name' => 'TH',
                'column_name' => 'gross',
            ],
            [

                'required' => 1,
                'field' => 'total_quantity',
                'description' => null,
                'mapping_type' => 'DECIMAL',
                'file_name' => 'TH',
                'column_name' => 'total_quantity',
            ],
            [

                'required' => 1,
                'field' => 'total_free_items_amount',
                'description' => null,
                'mapping_type' => 'DECIMAL',
                'file_name' => 'TH',
                'column_name' => 'total_free_items_amount',
            ],
            [

                'required' => 1,
                'field' => 'total_local_tax_amount',
                'description' => null,
                'mapping_type' => 'DECIMAL',
                'file_name' => 'TH',
                'column_name' => 'total_local_tax_amount',
            ],
            [

                'required' => 1,
                'field' => 'total_tax_amount',
                'description' => null,
                'mapping_type' => 'DECIMAL',
                'file_name' => 'TH',
                'column_name' => 'total_tax_amount',
            ],
            [

                'required' => 1,
                'field' => 'total_discount_amount',
                'description' => null,
                'mapping_type' => 'DECIMAL',
                'file_name' => 'TH',
                'column_name' => 'total_discount_amount',
            ],
            [

                'required' => 1,
                'field' => 'total_vat_exempt_amount',
                'description' => null,
                'mapping_type' => 'DECIMAL',
                'file_name' => 'TH',
                'column_name' => 'total_vat_exempt_amount',
            ],
            [

                'required' => 1,
                'field' => 'total_vat_deduct_amount',
                'description' => null,
                'mapping_type' => 'DECIMAL',
                'file_name' => 'TH',
                'column_name' => 'total_vat_deduct_amount',
            ],
            [

                'required' => 1,
                'field' => 'total_vatable_sales',
                'description' => null,
                'mapping_type' => 'DECIMAL',
                'file_name' => 'TH',
                'column_name' => 'total_vatable_sales',
            ],
            [

                'required' => 1,
                'field' => 'total_zero_rated_sales',
                'description' => null,
                'mapping_type' => 'DECIMAL',
                'file_name' => 'TH',
                'column_name' => 'total_zero_rated_sales',
            ],
            [

                'required' => 1,
                'field' => 'log_date',
                'description' => null,
                'mapping_type' => 'DATE',
                'file_name' => 'TH',
                'column_name' => 'log_date',
            ],
            [

                'required' => 1,
                'field' => 'order_number',
                'description' => null,
                'mapping_type' => 'INT',
                'file_name' => 'TH',
                'column_name' => 'order_number',
            ],
            [

                'required' => 0,
                'field' => 'table_number',
                'description' => null,
                'mapping_type' => 'VARCHAR',
                'file_name' => 'TH',
                'default_value' => '""',
                'column_name' => 'table_number',
            ],
            [

                'required' => 0,
                'field' => 'guest_count',
                'description' => null,
                'mapping_type' => 'INT',
                'file_name' => 'TH',
                'default_value' => 0,
                'column_name' => 'guest_count',
            ],
            // </ ** TRANSACTION HEAD ** > //

            // < ** TRANSACTION DETAIL ** > //
            [
                'required' => 1,
                'field' =>'official_receipt.*.split_number',
                'description' => null,
                'mapping_type' => 'INT',
                'file_name' => 'TD',
                'column_name' => 'split_number',
                'reference_column_name' => 'transaction_head_id',
                'head_reference' => 'TH.id',
            ],
            [
                'required' => 1,
                'field' =>'official_receipt.*.number',
                'description' => null,
                'mapping_type' => 'INT',
                'file_name' => 'TD',
                'column_name' => 'or_number',
                'reference_column_name' => 'transaction_head_id',
                'head_reference' => 'TH.id',
            ],
            [
                'required' => 1,
                'field' =>'official_receipt.*.total',
                'description' => null,
                'mapping_type' => 'DECIMAL',
                'file_name' => 'TD',
                'column_name' => 'total',
                'reference_column_name' => 'transaction_head_id',
                'head_reference' => 'TH.id',
            ],
            [
                'required' => 1,
                'field' =>'official_receipt.*.discount_amount',
                'description' => null,
                'mapping_type' => 'DECIMAL',
                'file_name' => 'TD',
                'column_name' => 'discount_amount',
                'reference_column_name' => 'transaction_head_id',
                'head_reference' => 'TH.id',
            ],
            [
                'required' => 1,
                'field' =>'official_receipt.*.free_items_amount',
                'description' => null,
                'mapping_type' => 'DECIMAL',
                'file_name' => 'TD',
                'column_name' => 'free_items_amount',
                'reference_column_name' => 'transaction_head_id',
                'head_reference' => 'TH.id',
            ],
            [
                'required' => 1,
                'field' =>'official_receipt.*.vat_deduct_amount',
                'description' => null,
                'mapping_type' => 'DECIMAL',
                'file_name' => 'TD',
                'column_name' => 'vat_deduct_amount',
                'reference_column_name' => 'transaction_head_id',
                'head_reference' => 'TH.id',
            ],
            [
                'required' => 1,
                'field' =>'official_receipt.*.vat_exempt_amount',
                'description' => null,
                'mapping_type' => 'DECIMAL',
                'file_name' => 'TD',
                'column_name' => 'vat_exempt_amount',
                'reference_column_name' => 'transaction_head_id',
                'head_reference' => 'TH.id',
            ],
            [
                'required' => 1,
                'field' =>'official_receipt.*.original_amount',
                'description' => null,
                'mapping_type' => 'DECIMAL',
                'file_name' => 'TD',
                'column_name' => 'original_amount',
                'reference_column_name' => 'transaction_head_id',
                'head_reference' => 'TH.id',
            ],
            [
                'required' => 1,
                'field' =>'official_receipt.*.quantity',
                'description' => null,
                'mapping_type' => 'DECIMAL',
                'file_name' => 'TD',
                'column_name' => 'quantity',
                'reference_column_name' => 'transaction_head_id',
                'head_reference' => 'TH.id',
            ],
            [
                'required' => 1,
                'field' =>'official_receipt.*.local_tax_amount',
                'description' => null,
                'mapping_type' => 'DECIMAL',
                'file_name' => 'TD',
                'column_name' => 'local_tax_amount',
                'reference_column_name' => 'transaction_head_id',
                'head_reference' => 'TH.id',
            ],
            [
                'required' => 1,
                'field' =>'official_receipt.*.tax_amount',
                'description' => null,
                'mapping_type' => 'DECIMAL',
                'file_name' => 'TD',
                'column_name' => 'tax_amount',
                'reference_column_name' => 'transaction_head_id',
                'head_reference' => 'TH.id',
            ],
            [
                'required' => 1,
                'field' =>'official_receipt.*.service_charge',
                'description' => null,
                'mapping_type' => 'DECIMAL',
                'file_name' => 'TD',
                'column_name' => 'service_charge',
                'reference_column_name' => 'transaction_head_id',
                'head_reference' => 'TH.id',
            ],
            [
                'required' => 1,
                'field' =>'official_receipt.*.vatable_sales',
                'description' => null,
                'mapping_type' => 'DECIMAL',
                'file_name' => 'TD',
                'column_name' => 'vatable_sales',
                'reference_column_name' => 'transaction_head_id',
                'head_reference' => 'TH.id',
            ],
            [
                'required' => 1,
                'field' =>'official_receipt.*.zero_rated_sales',
                'description' => null,
                'mapping_type' => 'DECIMAL',
                'file_name' => 'TD',
                'column_name' => 'zero_rated_sales',
                'reference_column_name' => 'transaction_head_id',
                'head_reference' => 'TH.id',
            ],
            [
                'required' => 1,
                'field' =>'official_receipt.*.eligible_amount_to_earn_points',
                'description' => null,
                'mapping_type' => 'DECIMAL',
                'file_name' => 'TD',
                'column_name' => 'eligible_amount_to_earn_points',
                'reference_column_name' => 'transaction_head_id',
                'head_reference' => 'TH.id',
            ],
            [
                'required' => 1,
                'field' =>'official_receipt.*.total_tender',
                'description' => null,
                'mapping_type' => 'DECIMAL',
                'file_name' => 'TD',
                'column_name' => 'total_tender',
                'reference_column_name' => 'transaction_head_id',
                'head_reference' => 'TH.id',
            ],
            [
                'required' => 1,
                'field' =>'official_receipt.*.cashier.id',
                'description' => null,
                'mapping_type' => 'VARCHAR',
                'file_name' => 'TD',
                'column_name' => 'cashier_id',
                'reference_column_name' => 'transaction_head_id',
                'head_reference' => 'TH.id',
            ],
            [
                'required' => 1,
                'field' =>'official_receipt.*.cashier.name',
                'description' => null,
                'mapping_type' => 'VARCHAR',
                'file_name' => 'TD',
                'column_name' => 'cashier_name',
                'reference_column_name' => 'transaction_head_id',
                'head_reference' => 'TH.id',
            ],
            [
                'required' => 1,
                'field' =>'official_receipt.*.customer.id',
                'description' => null,
                'mapping_type' => 'VARCHAR',
                'file_name' => 'TD',
                'column_name' => 'customer_id',
                'reference_column_name' => 'transaction_head_id',
                'head_reference' => 'TH.id',
            ],
            [
                'required' => 1,
                'field' =>'official_receipt.*.customer.type',
                'description' => null,
                'mapping_type' => 'INT',
                'file_name' => 'TD',
                'column_name' => 'customer_type',
                'reference_column_name' => 'transaction_head_id',
                'head_reference' => 'TH.id',
            ],
            [
                'required' => 1,
                'field' =>'official_receipt.*.customer.name',
                'description' => null,
                'mapping_type' => 'VARCHAR',
                'file_name' => 'TD',
                'column_name' => 'customer_name',
                'reference_column_name' => 'transaction_head_id',
                'head_reference' => 'TH.id',
            ],
            [
                'required' => 1,
                'field' =>'official_receipt.*.customer.address',
                'description' => null,
                'mapping_type' => 'VARCHAR',
                'file_name' => 'TD',
                'column_name' => 'customer_address',
                'reference_column_name' => 'transaction_head_id',
                'head_reference' => 'TH.id',
            ],
            // </ ** TRANSACTION DETAIL ** > //

            // < ** TRANSACTION DETAIL DISCOUNT ** > //
            [
                'required' => 1,
                'field' => 'official_receipt.*.discount.*.id',
                'description' => null,
                'mapping_type' => 'VARCHAR',
                'file_name' => 'TDD',
                'column_name' => 'discount_id',
                'reference_column_name' => 'transaction_detail_id',
                'head_reference' => 'TD.id',
            ],
            [
                'required' => 1,
                'field' => 'official_receipt.*.discount.*.mandated',
                'description' => null,
                'mapping_type' => 'INT',
                'file_name' => 'TDD',
                'column_name' => 'mandated',
                'reference_column_name' => 'transaction_detail_id',
                'head_reference' => 'TD.id',
            ],
            [
                'required' => 1,
                'field' => 'official_receipt.*.discount.*.title',
                'description' => null,
                'mapping_type' => 'VARCHAR',
                'file_name' => 'TDD',
                'column_name' => 'title',
                'reference_column_name' => 'transaction_detail_id',
                'head_reference' => 'TD.id',
            ],
            [
                'required' => 1,
                'field' => 'official_receipt.*.discount.*.total',
                'description' => null,
                'mapping_type' => 'DECIMAL',
                'file_name' => 'TDD',
                'column_name' => 'total',
                'reference_column_name' => 'transaction_detail_id',
                'head_reference' => 'TD.id',
            ],
            [
                'required' => 1,
                'field' => 'official_receipt.*.discount.*.amount_discount',
                'description' => null,
                'mapping_type' => 'DECIMAL',
                'file_name' => 'TDD',
                'column_name' => 'amount_discount',
                'reference_column_name' => 'transaction_detail_id',
                'head_reference' => 'TD.id',
            ],
            [
                'required' => 1,
                'field' => 'official_receipt.*.discount.*.vat_deduct',
                'description' => null,
                'mapping_type' => 'DECIMAL',
                'file_name' => 'TDD',
                'column_name' => 'vat_deduct',
                'reference_column_name' => 'transaction_detail_id',
                'head_reference' => 'TD.id',
            ],
            // </ ** TRANSACTION DETAIL DISCOUNT ** > //

            // < ** PAYMENT METHOD ** > //
            [
                'required' => 1,
                'field' =>'official_receipt.*.payment_method.*.id',
                'description' => null, 
                'mapping_type' => 'VARCHAR',
                'file_name' => 'PM',
                'column_name' => 'payment_method_id',
                'reference_column_name' => 'transaction_detail_id',
                'head_reference' => 'TD.id',
            ],
            [
                'required' => 1,
                'field' =>'official_receipt.*.payment_method.*.title',
                'description' => null,
                'mapping_type' => 'VARCHAR',
                'file_name' => 'PM',
                'column_name' => 'title',
                'reference_column_name' => 'transaction_detail_id',
                'head_reference' => 'TD.id',
            ],
            [
                'required' => 1,
                'field' =>'official_receipt.*.payment_method.*.total',
                'description' => null,
                'mapping_type' => 'DECIMAL',
                'file_name' => 'PM',
                'column_name' => 'total',
                'reference_column_name' => 'transaction_detail_id',
                'head_reference' => 'TD.id',
            ],
            [
                'required' => 1,
                'field' =>'official_receipt.*.payment_method.*.account_number',
                'description' => null,
                'mapping_type' => 'VARCHAR',
                'file_name' => 'PM',
                'column_name' => 'account_number',
                'reference_column_name' => 'transaction_detail_id',
                'head_reference' => 'TD.id',
            ],
            // </ ** PAYMENT METHOD ** > //

            // < ** PRODUCT ** > //
            [
                'required' => 1,
                'field' => 'official_receipt.*.product.*.id',
                'description' => null,
                'mapping_type' => 'VARCHAR',
                'file_name' => 'PR',
                'column_name' => 'product_id',
                'reference_column_name' => 'transaction_detail_id',
                'head_reference' => 'TD.id',
            ],
            [
                'required' => 1,
                'field' => 'official_receipt.*.product.*.menu_code',
                'description' => null,
                'mapping_type' => 'VARCHAR',
                'file_name' => 'PR',
                'column_name' => 'menu_code',
                'reference_column_name' => 'transaction_detail_id',
                'head_reference' => 'TD.id',
            ],
            [
                'required' => 1,
                'field' => 'official_receipt.*.product.*.name',
                'description' => null,
                'mapping_type' => 'VARCHAR',
                'file_name' => 'PR',
                'column_name' => 'name',
                'reference_column_name' => 'transaction_detail_id',
                'head_reference' => 'TD.id',
            ],
            [
                'required' => 1,
                'field' => 'official_receipt.*.product.*.description',
                'description' => null,
                'mapping_type' => 'VARCHAR',
                'file_name' => 'PR',
                'column_name' => 'description',
                'reference_column_name' => 'transaction_detail_id',
                'head_reference' => 'TD.id',
            ],
            [
                'required' => 1,
                'field' => 'official_receipt.*.product.*.long_description',
                'description' => null,
                'mapping_type' => 'VARCHAR',
                'file_name' => 'PR',
                'column_name' => 'long_description',
                'reference_column_name' => 'transaction_detail_id',
                'head_reference' => 'TD.id',
            ],
            [
                'required' => 1,
                'field' => 'official_receipt.*.product.*.quantity',
                'description' => null,
                'mapping_type' => 'DECIMAL',
                'file_name' => 'PR',
                'column_name' => 'quantity',
                'reference_column_name' => 'transaction_detail_id',
                'head_reference' => 'TD.id',
            ],
            [
                'required' => 1,
                'field' => 'official_receipt.*.product.*.tax_percentage',
                'description' => null,
                'mapping_type' => 'DECIMAL',
                'file_name' => 'PR',
                'default_value' => 12.0,
                'column_name' => 'tax_percentage',
                'reference_column_name' => 'transaction_detail_id',
                'head_reference' => 'TD.id',
            ],
            [
                'required' => 1,
                'field' => 'official_receipt.*.product.*.is_free',
                'description' => null,
                'mapping_type' => 'INT',
                'file_name' => 'PR',
                'column_name' => 'is_free',
                'reference_column_name' => 'transaction_detail_id',
                'head_reference' => 'TD.id',
            ],
            [
                'required' => 1,
                'field' => 'official_receipt.*.product.*.is_vatable',
                'description' => null,
                'mapping_type' => 'INT',
                'file_name' => 'PR',
                'column_name' => 'is_vatable',
                'reference_column_name' => 'transaction_detail_id',
                'head_reference' => 'TD.id',
            ],
            [
                'required' => 1,
                'field' => 'official_receipt.*.product.*.original_price',
                'description' => null,
                'mapping_type' => 'DECIMAL',
                'file_name' => 'PR',
                'column_name' => 'original_price',
                'reference_column_name' => 'transaction_detail_id',
                'head_reference' => 'TD.id',
            ],
            [
                'required' => 1,
                'field' => 'official_receipt.*.product.*.price',
                'description' => null,
                'mapping_type' => 'DECIMAL',
                'file_name' => 'PR',
                'column_name' => 'price',
                'reference_column_name' => 'transaction_detail_id',
                'head_reference' => 'TD.id',
            ],
            [
                'required' => 1,
                'field' => 'official_receipt.*.product.*.total_addon',
                'description' => null,
                'mapping_type' => 'DECIMAL',
                'file_name' => 'PR',
                'column_name' => 'total_addon',
                'reference_column_name' => 'transaction_detail_id',
                'head_reference' => 'TD.id',
            ],
            [
                'required' => 1,
                'field' => 'official_receipt.*.product.*.total_amount',
                'description' => null,
                'mapping_type' => 'DECIMAL',
                'file_name' => 'PR',
                'column_name' => 'total_amount',
                'reference_column_name' => 'transaction_detail_id',
                'head_reference' => 'TD.id',
            ],
            [
                'required' => 1,
                'field' => 'official_receipt.*.product.*.amount_discount',
                'description' => null,
                'mapping_type' => 'DECIMAL',
                'file_name' => 'PR',
                'column_name' => 'amount_discount',
                'reference_column_name' => 'transaction_detail_id',
                'head_reference' => 'TD.id',
            ],
            [
                'required' => 1,
                'field' => 'official_receipt.*.product.*.vatable_sales',
                'description' => null,
                'mapping_type' => 'DECIMAL',
                'file_name' => 'PR',
                'column_name' => 'vatable_sales',
                'reference_column_name' => 'transaction_detail_id',
                'head_reference' => 'TD.id',
            ],
            [
                'required' => 1,
                'field' => 'official_receipt.*.product.*.zero_rated_sales',
                'description' => null,
                'mapping_type' => 'DECIMAL',
                'file_name' => 'PR',
                'column_name' => 'zero_rated_sales',
                'reference_column_name' => 'transaction_detail_id',
                'head_reference' => 'TD.id',
            ],
            [
                'required' => 1,
                'field' => 'official_receipt.*.product.*.tax',
                'description' => null,
                'mapping_type' => 'DECIMAL',
                'file_name' => 'PR',
                'column_name' => 'tax',
                'reference_column_name' => 'transaction_detail_id',
                'head_reference' => 'TD.id',
            ],
            [
                'required' => 1,
                'field' => 'official_receipt.*.product.*.vat_exempt',
                'description' => null,
                'mapping_type' => 'DECIMAL',
                'file_name' => 'PR',
                'column_name' => 'vat_exempt',
                'reference_column_name' => 'transaction_detail_id',
                'head_reference' => 'TD.id',
            ],
            [
                'required' => 1,
                'field' => 'official_receipt.*.product.*.vat_deduct',
                'description' => null,
                'mapping_type' => 'DECIMAL',
                'file_name' => 'PR',
                'column_name' => 'vat_deduct',
                'reference_column_name' => 'transaction_detail_id',
                'head_reference' => 'TD.id',
            ],
            [
                'required' => 1,
                'field' => 'official_receipt.*.product.*.split_number',
                'description' => null,
                'mapping_type' => 'INT',
                'file_name' => 'PR',
                'column_name' => 'split_number',
                'reference_column_name' => 'transaction_detail_id',
                'head_reference' => 'TD.id',
            ],
            [
                'required' => 1,
                'field' => 'official_receipt.*.product.*.order_type.id',
                'description' => null,
                'mapping_type' => 'VARCHAR',
                'file_name' => 'PR',
                'column_name' => 'order_type_id',
                'reference_column_name' => 'transaction_detail_id',
                'head_reference' => 'TD.id',
            ],
            [
                'required' => 1,
                'field' => 'official_receipt.*.product.*.order_type.name',
                'description' => null,
                'mapping_type' => 'VARCHAR',
                'file_name' => 'PR',
                'column_name' => 'order_type_name',
                'reference_column_name' => 'transaction_detail_id',
                'head_reference' => 'TD.id',
            ],
            [
                'required' => 1,
                'field' => 'official_receipt.*.product.*.category.id',
                'description' => null,
                'mapping_type' => 'VARCHAR',
                'file_name' => 'PR',
                'column_name' => 'category_id',
                'reference_column_name' => 'transaction_detail_id',
                'head_reference' => 'TD.id',
            ],
            [
                'required' => 1,
                'field' => 'official_receipt.*.product.*.category.name',
                'description' => null,
                'mapping_type' => 'VARCHAR',
                'file_name' => 'PR',
                'column_name' => 'category_name',
                'reference_column_name' => 'transaction_detail_id',
                'head_reference' => 'TD.id',
            ],
            [
                'required' => 1,
                'field' => 'official_receipt.*.product.*.price_override_details.price',
                'description' => null,
                'mapping_type' => 'DECIMAL',
                'file_name' => 'PR',
                'column_name' => 'price_override_price',
                'reference_column_name' => 'transaction_detail_id',
                'head_reference' => 'TD.id',
                'nullable' => 1,
            ],
            [
                'required' => 1,
                'field' => 'official_receipt.*.product.*.price_override_details.approved_by',
                'description' => null,
                'mapping_type' => 'VARCHAR',
                'file_name' => 'PR',
                'column_name' => 'price_override_approved_by',
                'reference_column_name' => 'transaction_detail_id',
                'head_reference' => 'TD.id',
                'nullable' => 1,
            ],
            [
                'required' => 1,
                'field' => 'official_receipt.*.product.*.price_override_details.approved_date',
                'description' => null,
                'mapping_type' => 'DATETIME',
                'file_name' => 'PR',
                'column_name' => 'price_override_approved_date',
                'reference_column_name' => 'transaction_detail_id',
                'head_reference' => 'TD.id',
                'nullable' => 1,
            ],
            // </ ** PRODUCT ** > //

            // < ** ADD ONS ** > //
            [
                'required' => 1,
                'field' => 'official_receipt.*.product.*.addon.*.id',
                'description' => null,
                'mapping_type' => 'VARCHAR',
                'file_name' => 'AD',
                'column_name' => 'id',
                'reference_column_name' => 'transaction_product_id',
                'head_reference' => 'PR.id',
            ],
            [
                'required' => 1,
                'field' => 'official_receipt.*.product.*.addon.*.product_bid',
                'description' => null,
                'mapping_type' => 'VARCHAR',
                'file_name' => 'AD',
                'column_name' => 'product_id',
                'reference_column_name' => 'transaction_product_id',
                'head_reference' => 'PR.id',
            ],
            [
                'required' => 1,
                'field' => 'official_receipt.*.product.*.addon.*.name',
                'description' => null,
                'mapping_type' => 'VARCHAR',
                'file_name' => 'AD',
                'column_name' => 'name',
                'reference_column_name' => 'transaction_product_id',
                'head_reference' => 'PR.id',
            ],
            [
                'required' => 1,
                'field' => 'official_receipt.*.product.*.addon.*.quantity',
                'description' => null,
                'mapping_type' => 'DECIMAL',
                'file_name' => 'AD',
                'column_name' => 'quantity',
                'reference_column_name' => 'transaction_product_id',
                'head_reference' => 'PR.id',
            ],
            [
                'required' => 1,
                'field' => 'official_receipt.*.product.*.addon.*.original_price',
                'description' => null,
                'mapping_type' => 'DECIMAL',
                'file_name' => 'AD',
                'column_name' => 'original_price',
                'reference_column_name' => 'transaction_product_id',
                'head_reference' => 'PR.id',
            ],
            [
                'required' => 1,
                'field' => 'official_receipt.*.product.*.addon.*.price',
                'description' => null,
                'mapping_type' => 'DECIMAL',
                'file_name' => 'AD',
                'column_name' => 'price',
                'reference_column_name' => 'transaction_product_id',
                'head_reference' => 'PR.id',
            ],
            [
                'required' => 1,
                'field' => 'official_receipt.*.product.*.addon.*.total_amount',
                'description' => null,
                'mapping_type' => 'DECIMAL',
                'file_name' => 'AD',
                'default_value' => 0.000000,
                'column_name' => 'total_amount',
                'reference_column_name' => 'transaction_product_id',
                'head_reference' => 'PR.id',
            ],
            // </ ** ADD ONS ** > //

            // < ** PRODUCT DISCOUNT ** > //
            [
                'required' => 1,
                'field' => 'official_receipt.*.product.*.discount.*.id',
                'description' => null,
                'mapping_type' => 'VARCHAR',
                'file_name' => 'PD',
                'column_name' => 'id',
                'reference_column_name' => 'transaction_product_id',
                'head_reference' => 'PR.id',
            ],
            [
                'required' => 1,
                'field' => 'official_receipt.*.product.*.discount.*.mandated',
                'description' => null,
                'mapping_type' => 'INT',
                'file_name' => 'PD',
                'column_name' => 'mandated',
                'reference_column_name' => 'transaction_product_id',
                'head_reference' => 'PR.id',
            ],
            [
                'required' => 1,
                'field' => 'official_receipt.*.product.*.discount.*.title',
                'description' => null,
                'mapping_type' => 'VARCHAR',
                'file_name' => 'PD',
                'default_value' => '""',
                'column_name' => 'title',
                'reference_column_name' => 'transaction_product_id',
                'head_reference' => 'PR.id',
            ],
            [
                'required' => 1,
                'field' => 'official_receipt.*.product.*.discount.*.total',
                'description' => null,
                'mapping_type' => 'DECIMAL',
                'file_name' => 'PD',
                'column_name' => 'total',
                'reference_column_name' => 'transaction_product_id',
                'head_reference' => 'PR.id',
            ],
            [
                'required' => 1,
                'field' => 'official_receipt.*.product.*.discount.*.amount_discount',
                'description' => null,
                'mapping_type' => 'DECIMAL',
                'file_name' => 'PD',
                'column_name' => 'amount_discount',
                'reference_column_name' => 'transaction_product_id',
                'head_reference' => 'PR.id',
            ],
            [
                'required' => 1,
                'field' => 'official_receipt.*.product.*.discount.*.vat_deduct',
                'description' => null,
                'mapping_type' => 'DECIMAL',
                'file_name' => 'PD',
                'column_name' => 'vat_deduct',
                'reference_column_name' => 'transaction_product_id',
                'head_reference' => 'PR.id',
            ],
            [
                'required' => 1,
                'field' => 'official_receipt.*.product.*.discount.*.vat_exempt',
                'description' => null,
                'mapping_type' => 'DECIMAL',
                'file_name' => 'PD',
                'column_name' => 'vat_exempt',
                'reference_column_name' => 'transaction_product_id',
                'head_reference' => 'PR.id',
            ],
            // </ ** PRODUCT DISCOUNT ** > //
        ];

        foreach ($fieldMappingPresetDetail as $value) {
            $fieldMappingPreset->detail()->create($value);
        }
    }

    /**
     * Reverts the database seeder.
     */
    public function down(): void
    {
        FieldMappingPreset::where([
            'preset_name' => 'Transaction (Default)',
            'data_entry' => 'transaction',
        ])->forceDelete();
    }
}
