<?php

use App\Entities\FieldMapping;
use App\Entities\FieldMappingDetail;
use Eighty8\LaravelSeeder\Migration\MigratableSeeder;
use Eighty8\LaravelSeeder\Repository\DisableForeignKeysTrait;

class CdisZreadFields extends MigratableSeeder
{
    use DisableForeignKeysTrait;

    /**
     * Run the database seeder.
     */
    public function run(): void
    {
        $zread = [
            'type' => '2',
            'api_version_name' => 'Zread default',
            'api_endpoint' => 'Zread',
            'status' => 1,
            'created_by' => 1,
        ];

        $field_map = FieldMapping::create($zread);

        $field_mapping_details = [
            [
                'field_mapping_bid' => $field_map->bid,
                'required' => 0,
                'field' => 'day_end_report_number',
                'description' => null,
                'mapping_type' => 'VARCHAR',
                'file_name' => 'ZH',
                'default_value' => '""',
                'column_name' => 'day_end_report_number',
            ],
            [
                'field_mapping_bid' => $field_map->bid,
                'required' => 0,
                'field' => 'administrator',
                'description' => null,
                'mapping_type' => 'VARCHAR',
                'file_name' => 'ZH',
                'default_value' => '""',
                'column_name' => 'administrator',
            ],
            [
                'field_mapping_bid' => $field_map->bid,
                'required' => 0,
                'field' => 'cashier',
                'description' => null,
                'mapping_type' => 'VARCHAR',
                'file_name' => 'ZH',
                'default_value' => '""',
                'column_name' => 'cashier',
            ],
            [
                'field_mapping_bid' => $field_map->bid,
                'required' => 0,
                'field' => 'log_date',
                'description' => null,
                'mapping_type' => 'VARCHAR',
                'file_name' => 'ZH',
                'default_value' => '""',
                'column_name' => 'log_date',
            ],
            [
                'field_mapping_bid' => $field_map->bid,
                'required' => 0,
                'field' => 'date_time',
                'description' => null,
                'mapping_type' => 'VARCHAR',
                'file_name' => 'ZH',
                'default_value' => '""',
                'column_name' => 'date_time',
            ],
            [
                'field_mapping_bid' => $field_map->bid,
                'required' => 0,
                'field' => 'terminal_number',
                'description' => null,
                'mapping_type' => 'VARCHAR',
                'file_name' => 'ZH',
                'default_value' => '""',
                'column_name' => 'terminal_number',
            ],
            [
                'field_mapping_bid' => $field_map->bid,
                'required' => 0,
                'field' => 'branch_code',
                'description' => null,
                'mapping_type' => 'VARCHAR',
                'file_name' => 'ZH',
                'default_value' => '""',
                'column_name' => 'branch_code',
            ],
            [
                'field_mapping_bid' => $field_map->bid,
                'required' => 0,
                'field' => 'guest_count',
                'description' => null,
                'mapping_type' => 'VARCHAR',
                'file_name' => 'ZH',
                'default_value' => '""',
                'column_name' => 'guest_count',
            ],
            [
                'field_mapping_bid' => $field_map->bid,
                'required' => 0,
                'field' => 'gross_sales_amount',
                'description' => null,
                'mapping_type' => 'DECIMAL',
                'file_name' => 'ZH',
                'default_value' => 0.00,
                'column_name' => 'gross_sales_amount',
            ],
            [
                'field_mapping_bid' => $field_map->bid,
                'required' => 0,
                'field' => 'transaction_count',
                'description' => null,
                'mapping_type' => 'INT',
                'file_name' => 'ZH',
                'default_value' => 0,
                'column_name' => 'transaction_count',
            ],
            [
                'field_mapping_bid' => $field_map->bid,
                'required' => 0,
                'field' => 'total_regular_discount_amount',
                'description' => null,
                'mapping_type' => 'DECIMAL',
                'file_name' => 'ZH',
                'default_value' => 0.00,
                'column_name' => 'total_regular_discount_amount',
            ],
            [
                'field_mapping_bid' => $field_map->bid,
                'required' => 0,
                'field' => 'mandated_discount_transaction_count',
                'description' => null,
                'mapping_type' => 'INT',
                'file_name' => 'ZH',
                'default_value' => 0,
                'column_name' => 'mandated_discount_transaction_count',
            ],
            [
                'field_mapping_bid' => $field_map->bid,
                'required' => 0,
                'field' => 'total_regular_discount_count',
                'description' => null,
                'mapping_type' => 'INT',
                'file_name' => 'ZH',
                'default_value' => 0,
                'column_name' => 'total_regular_discount_count',
            ],
            [
                'field_mapping_bid' => $field_map->bid,
                'required' => 0,
                'field' => 'regular_discount_name',
                'description' => null,
                'mapping_type' => 'DECIMAL',
                'file_name' => 'ZH',
                'default_value' => 0.00,
                'column_name' => 'name',
            ],
            [
                'field_mapping_bid' => $field_map->bid,
                'required' => 0,
                'field' => 'regular_discount_count',
                'description' => null,
                'mapping_type' => 'DECIMAL',
                'file_name' => 'ZH',
                'default_value' => 0.00,
                'column_name' => 'count',
            ],
            [
                'field_mapping_bid' => $field_map->bid,
                'required' => 0,
                'field' => 'regular_discount_amount',
                'description' => null,
                'mapping_type' => 'DECIMAL',
                'file_name' => 'ZH',
                'default_value' => 0.00,
                'column_name' => 'amount',
            ],
            [
                'field_mapping_bid' => $field_map->bid,
                'required' => 0,
                'field' => 'senior_transaction_count',
                'description' => null,
                'mapping_type' => 'INT',
                'file_name' => 'ZH',
                'default_value' => 0.00,
                'column_name' => 'senior_transaction_count',
            ],
            [
                'field_mapping_bid' => $field_map->bid,
                'required' => 0,
                'field' => 'senior_discount_amount',
                'description' => null,
                'mapping_type' => 'DECIMAL',
                'file_name' => 'ZH',
                'default_value' => 0.00,
                'column_name' => 'senior_discount_amount',
            ],
            [
                'field_mapping_bid' => $field_map->bid,
                'required' => 0,
                'field' => 'sc_vat_deduction_amount',
                'description' => null,
                'mapping_type' => 'DECIMAL',
                'file_name' => 'ZH',
                'default_value' => 0.00,
                'column_name' => 'sc_vat_deduction_amount',
            ],
            [
                'field_mapping_bid' => $field_map->bid,
                'required' => 0,
                'field' => 'pwd_transaction_count',
                'description' => null,
                'mapping_type' => 'INT',
                'file_name' => 'ZH',
                'default_value' => 0,
                'column_name' => 'pwd_transaction_count',
            ],
            [
                'field_mapping_bid' => $field_map->bid,
                'required' => 0,
                'field' => 'pwd_transaction_amount',
                'description' => null,
                'mapping_type' => 'DECIMAL',
                'file_name' => 'ZH',
                'default_value' => 0.00,
                'column_name' => 'pwd_transaction_amount',
            ],
            [
                'field_mapping_bid' => $field_map->bid,
                'required' => 0,
                'field' => 'pwd_vat_deduction',
                'description' => null,
                'mapping_type' => 'DECIMAL',
                'file_name' => 'ZH',
                'default_value' => 0.00,
                'column_name' => 'pwd_vat_deduction',
            ],
            [
                'field_mapping_bid' => $field_map->bid,
                'required' => 0,
                'field' => 'diplomat_transaction_count',
                'description' => null,
                'mapping_type' => 'INT',
                'file_name' => 'ZH',
                'default_value' => 0,
                'column_name' => 'diplomat_transaction_count',
            ],
            [
                'field_mapping_bid' => $field_map->bid,
                'required' => 0,
                'field' => 'diplomat_vat_deduction',
                'description' => null,
                'mapping_type' => 'DECIMAL',
                'file_name' => 'ZH',
                'default_value' => 0.00,
                'column_name' => 'diplomat_vat_deduction',
            ],
            [
                'field_mapping_bid' => $field_map->bid,
                'required' => 0,
                'field' => 'vatable_sales',
                'description' => null,
                'mapping_type' => 'DECIMAL',
                'file_name' => 'ZH',
                'default_value' => 0.00,
                'column_name' => 'vatable_sales',
            ],
            [
                'field_mapping_bid' => $field_map->bid,
                'required' => 0,
                'field' => 'vat_amount',
                'description' => null,
                'mapping_type' => 'DECIMAL',
                'file_name' => 'ZH',
                'default_value' => 0.00,
                'column_name' => 'vat_amount',
            ],
            [
                'field_mapping_bid' => $field_map->bid,
                'required' => 0,
                'field' => 'vat_exempt_sales',
                'description' => null,
                'mapping_type' => 'DECIMAL',
                'file_name' => 'ZH',
                'default_value' => 0.00,
                'column_name' => 'vat_exempt_sales',
            ],
            [
                'field_mapping_bid' => $field_map->bid,
                'required' => 0,
                'field' => 'less_mandated_vat_and_discount',
                'description' => null,
                'mapping_type' => 'DECIMAL',
                'file_name' => 'ZH',
                'default_value' => 0.00,
                'column_name' => 'less_mandated_vat_and_discount',
            ],
            [
                'field_mapping_bid' => $field_map->bid,
                'required' => 0,
                'field' => 'net_of_vat_exempt',
                'description' => null,
                'mapping_type' => 'DECIMAL',
                'file_name' => 'ZH',
                'default_value' => 0.00,
                'column_name' => 'net_of_vat_exempt',
            ],
            [
                'field_mapping_bid' => $field_map->bid,
                'required' => 0,
                'field' => 'zero_rated_sales',
                'description' => null,
                'mapping_type' => 'DECIMAL',
                'file_name' => 'ZH',
                'default_value' => 0.00,
                'column_name' => 'zero_rated_sales',
            ],
            [
                'field_mapping_bid' => $field_map->bid,
                'required' => 0,
                'field' => 'non_vat_sales',
                'description' => null,
                'mapping_type' => 'DECIMAL',
                'file_name' => 'ZH',
                'default_value' => 0.00,
                'column_name' => 'non_vat_sales',
            ],
            [
                'field_mapping_bid' => $field_map->bid,
                'required' => 0,
                'field' => 'subtotal',
                'description' => null,
                'mapping_type' => 'DECIMAL',
                'file_name' => 'ZH',
                'default_value' => 0.00,
                'column_name' => 'subtotal',
            ],
            [
                'field_mapping_bid' => $field_map->bid,
                'required' => 0,
                'field' => 'service_charge',
                'description' => null,
                'mapping_type' => 'DECIMAL',
                'file_name' => 'ZH',
                'default_value' => 0.00,
                'column_name' => 'service_charge',
            ],
            [
                'field_mapping_bid' => $field_map->bid,
                'required' => 0,
                'field' => 'net_total',
                'description' => null,
                'mapping_type' => 'DECIMAL',
                'file_name' => 'ZH',
                'default_value' => 0.00,
                'column_name' => 'net_total',
            ],
            [
                'field_mapping_bid' => $field_map->bid,
                'required' => 0,
                'field' => 'beginning_or',
                'description' => null,
                'mapping_type' => 'VARCHAR',
                'file_name' => 'ZH',
                'default_value' => '""',
                'column_name' => 'beginning_or',
            ],
            [
                'field_mapping_bid' => $field_map->bid,
                'required' => 0,
                'field' => 'ending_or',
                'description' => null,
                'mapping_type' => 'VARCHAR',
                'file_name' => 'ZH',
                'default_value' => '""',
                'column_name' => 'ending_or',
            ],
            [
                'field_mapping_bid' => $field_map->bid,
                'required' => 0,
                'field' => 'no_sales_transaction_count',
                'description' => null,
                'mapping_type' => 'INT',
                'file_name' => 'ZH',
                'default_value' => 0,
                'column_name' => 'no_sales_transaction_count',
            ],
            [
                'field_mapping_bid' => $field_map->bid,
                'required' => 0,
                'field' => 'void_transactions_count',
                'description' => null,
                'mapping_type' => 'INT',
                'file_name' => 'ZH',
                'default_value' => 0,
                'column_name' => 'void_transactions_count',
            ],
            [
                'field_mapping_bid' => $field_map->bid,
                'required' => 0,
                'field' => 'void_transactions_amount',
                'description' => null,
                'mapping_type' => 'DECIMAL',
                'file_name' => 'ZH',
                'default_value' => 0.00,
                'column_name' => 'void_transactions_amount',
            ],
            [
                'field_mapping_bid' => $field_map->bid,
                'required' => 0,
                'field' => 'void_items_count',
                'description' => null,
                'mapping_type' => 'INT',
                'file_name' => 'ZH',
                'default_value' => 0,
                'column_name' => 'void_items_count',
            ],
            [
                'field_mapping_bid' => $field_map->bid,
                'required' => 0,
                'field' => 'void_items_amount',
                'description' => null,
                'mapping_type' => 'DECIMAL',
                'file_name' => 'ZH',
                'default_value' => 0.00,
                'column_name' => 'void_items_amount',
            ],
            [
                'field_mapping_bid' => $field_map->bid,
                'required' => 0,
                'field' => 'refunds_count',
                'description' => null,
                'mapping_type' => 'INT',
                'file_name' => 'ZH',
                'default_value' => 0,
                'column_name' => 'refunds_count',
            ],
            [
                'field_mapping_bid' => $field_map->bid,
                'required' => 0,
                'field' => 'refunds_amount',
                'description' => null,
                'mapping_type' => 'DECIMAL',
                'file_name' => 'ZH',
                'default_value' => 0.00,
                'column_name' => 'refunds_amount',
            ],
            [
                'field_mapping_bid' => $field_map->bid,
                'required' => 0,
                'field' => 'tender_detail_name',
                'description' => null,
                'mapping_type' => 'VARCHAR',
                'file_name' => 'ZH',
                'default_value' => '""',
                'column_name' => 'name',
            ],
            [
                'field_mapping_bid' => $field_map->bid,
                'required' => 0,
                'field' => 'tender_detail_count',
                'description' => null,
                'mapping_type' => 'INT',
                'file_name' => 'ZH',
                'default_value' => 0,
                'column_name' => 'count',
            ],
            [
                'field_mapping_bid' => $field_map->bid,
                'required' => 0,
                'field' => 'tender_detail_amount',
                'description' => null,
                'mapping_type' => 'DECIMAL',
                'file_name' => 'ZH',
                'default_value' => 0.00,
                'column_name' => 'amount',
            ],
            [
                'field_mapping_bid' => $field_map->bid,
                'required' => 0,
                'field' => 'total_tenders_count',
                'description' => null,
                'mapping_type' => 'INT',
                'file_name' => 'ZH',
                'default_value' => 0,
                'column_name' => 'total_tenders_count',
            ],
            [
                'field_mapping_bid' => $field_map->bid,
                'required' => 0,
                'field' => 'total_tenders_amount',
                'description' => null,
                'mapping_type' => 'DECIMAL',
                'file_name' => 'ZH',
                'default_value' => 0.00,
                'column_name' => 'total_tenders_amount',
            ],
            [
                'field_mapping_bid' => $field_map->bid,
                'required' => 0,
                'field' => 'add_initial_cash_amount',
                'description' => null,
                'mapping_type' => 'DECIMAL',
                'file_name' => 'ZH',
                'default_value' => 0.00,
                'column_name' => 'add_initial_cash_amount',
            ],
            [
                'field_mapping_bid' => $field_map->bid,
                'required' => 0,
                'field' => 'less_withdrawals_amount',
                'description' => null,
                'mapping_type' => 'DECIMAL',
                'file_name' => 'ZH',
                'default_value' => 0.00,
                'column_name' => 'less_withdrawals_amount',
            ],
            [
                'field_mapping_bid' => $field_map->bid,
                'required' => 0,
                'field' => 'add_cash_returns_amount',
                'description' => null,
                'mapping_type' => 'DECIMAL',
                'file_name' => 'ZH',
                'default_value' => 0.00,
                'column_name' => 'add_cash_returns_amount',
            ],
            [
                'field_mapping_bid' => $field_map->bid,
                'required' => 0,
                'field' => 'total_drawer_amount',
                'description' => null,
                'mapping_type' => 'DECIMAL',
                'file_name' => 'ZH',
                'default_value' => 0.00,
                'column_name' => 'total_drawer_amount',
            ],
            [
                'field_mapping_bid' => $field_map->bid,
                'required' => 0,
                'field' => 'cash_breakdown_detail_denomination',
                'description' => null,
                'mapping_type' => 'DECIMAL',
                'file_name' => 'ZH',
                'default_value' => 0.00,
                'column_name' => 'denomination',
            ],
            [
                'field_mapping_bid' => $field_map->bid,
                'required' => 0,
                'field' => 'cash_breakdown_detail_count',
                'description' => null,
                'mapping_type' => 'INT',
                'file_name' => 'ZH',
                'default_value' => 0,
                'column_name' => 'count',
            ],
            [
                'field_mapping_bid' => $field_map->bid,
                'required' => 0,
                'field' => 'cash_breakdown_detail_amount',
                'description' => null,
                'mapping_type' => 'DECIMAL',
                'file_name' => 'ZH',
                'default_value' => 0.00,
                'column_name' => 'amount',
            ],
            [
                'field_mapping_bid' => $field_map->bid,
                'required' => 0,
                'field' => 'total_cash_breakdown_amount',
                'description' => null,
                'mapping_type' => 'DECIMAL',
                'file_name' => 'ZH',
                'default_value' => 0.00,
                'column_name' => 'total_cash_breakdown_amount',
            ],
            [
                'field_mapping_bid' => $field_map->bid,
                'required' => 0,
                'field' => 'short_over_amount',
                'description' => null,
                'mapping_type' => 'DECIMAL',
                'file_name' => 'ZH',
                'default_value' => 0.00,
                'column_name' => 'short_over_amount',
            ],
            [
                'field_mapping_bid' => $field_map->bid,
                'required' => 0,
                'field' => 'cashier_sales_summary_name',
                'description' => null,
                'mapping_type' => 'VARCHAR',
                'file_name' => 'ZH',
                'default_value' => '""',
                'column_name' => 'name',
            ],
            [
                'field_mapping_bid' => $field_map->bid,
                'required' => 0,
                'field' => 'cashier_sales_summary_amount',
                'description' => null,
                'mapping_type' => 'DECIMAL',
                'file_name' => 'ZH',
                'default_value' => 0.00,
                'column_name' => 'amount',
            ],
            [
                'field_mapping_bid' => $field_map->bid,
                'required' => 0,
                'field' => 'total_cashier_sales_amount',
                'description' => null,
                'mapping_type' => 'DECIMAL',
                'file_name' => 'ZH',
                'default_value' => 0.00,
                'column_name' => 'total_cashier_sales_amount',
            ],
            [
                'field_mapping_bid' => $field_map->bid,
                'required' => 0,
                'field' => 'beginning_balance',
                'description' => null,
                'mapping_type' => 'DECIMAL',
                'file_name' => 'ZH',
                'default_value' => 0.00,
                'column_name' => 'beginning_balance',
            ],
            [
                'field_mapping_bid' => $field_map->bid,
                'required' => 0,
                'field' => 'ending_balance',
                'description' => null,
                'mapping_type' => 'DECIMAL',
                'file_name' => 'ZH',
                'default_value' => '""',
                'column_name' => 'ending_balance',
            ],
        ];

        foreach ($field_mapping_details as $value) {
            FieldMappingDetail::create($value);
        }
    }

    /**
     * Reverts the database seeder.
     */
    public function down(): void
    {
        // Remove your data
    }
}
