<?php

use App\Entities\FieldMapping;
use App\Entities\FieldMappingDetail;
use Eighty8\LaravelSeeder\Migration\MigratableSeeder;
use Eighty8\LaravelSeeder\Repository\DisableForeignKeysTrait;

class CdisTransactionFields extends MigratableSeeder
{
    use DisableForeignKeysTrait;

    /**
     * Run the database seeder.
     */
    public function run(): void
    {
        $transaction = [
            'type' => '2',
            'api_version_name' => 'Transaction default',
            'api_endpoint' => 'Transactions',
            'status' => 1,
            'created_by' => 1,
        ];

        FieldMapping::create($transaction);

        $field_mapping_details = [
            [
                'field_mapping_bid' => 1,
                'required' => 0,
                'field' => 'branch_code',
                'description' => null,
                'mapping_type' => 'INT',
                'file_name' => 'branch_code',
                'default_value' => '""',
                'column_name' => null,
            ],
            [
                'field_mapping_bid' => 1,
                'required' => 0,
                'field' => 'terminal_number',
                'description' => null,
                'mapping_type' => 'VARCHAR',
                'file_name' => 'terminal_number',
                'default_value' => '""',
                'column_name' => null,
            ],
            [
                'field_mapping_bid' => 1,
                'required' => 0,
                'field' => 'transaction_id',
                'description' => null,
                'mapping_type' => 'INT',
                'file_name' => 'transaction_id',
                'default_value' => '""',
                'column_name' => null,
            ],
            [
                'field_mapping_bid' => 1,
                'required' => 0,
                'field' => 'date',
                'description' => null,
                'mapping_type' => 'DATETIME',
                'file_name' => 'date',
                'default_value' => '""',
                'column_name' => null,
            ],
            [
                'field_mapping_bid' => 1,
                'required' => 0,
                'field' => 'amount',
                'description' => null,
                'mapping_type' => 'DECIMAL',
                'file_name' => 'amount',
                'default_value' => '""',
                'column_name' => null,
            ],
            [
                'field_mapping_bid' => 1,
                'required' => 0,
                'field' => 'transaction_type',
                'description' => null,
                'mapping_type' => 'INT',
                'file_name' => 'transaction_type',
                'default_value' => 0,
                'column_name' => null,
            ],
            [
                'field_mapping_bid' => 1,
                'required' => 0,
                'field' => 'is_zread',
                'description' => null,
                'mapping_type' => 'INT',
                'file_name' => 'is_zread',
                'default_value' => 0,
                'column_name' => null,
            ],
            [
                'field_mapping_bid' => 1,
                'required' => 0,
                'field' => 'status',
                'description' => null,
                'mapping_type' => 'INT',
                'file_name' => 'status',
                'default_value' => 1,
                'column_name' => null,
            ],
            [
                'field_mapping_bid' => 1, 
                'required' => 0, 
                'field' => 'type', 
                'description' => null, 
                'mapping_type' => 'INT', 
                'file_name' => 'type', 
                'default_value' => 1, 
                'column_name' => null,
            ],
            [
                
                'field_mapping_bid' => 1, 
                'required' => 0, 
                'field' => 'gross', 
                'description' => null, 
                'mapping_type' => 'DECIMAL', 
                'file_name' => 'gross', 
                'default_value' => 1, 
                'column_name' => null,
            ],
            [
                
                'field_mapping_bid' => 1, 
                'required' => 0, 
                'field' => 'total_quantity', 
                'description' => null, 
                'mapping_type' => 'DECIMAL', 
                'file_name' => 'total_quantity', 
                'default_value' => 1, 
                'column_name' => null,
            ],
            [
                
                'field_mapping_bid' => 1, 
                'required' => 0, 
                'field' => 'total_free_items_amount', 
                'description' => null, 
                'mapping_type' => 'DECIMAL', 
                'file_name' => 'total_free_items_amount', 
                'default_value' => 1, 
                'column_name' => null,
            ],
            [
                
                'field_mapping_bid' => 1, 
                'required' => 0, 
                'field' => 'total_local_tax_amount', 
                'description' => null, 
                'mapping_type' => 'DECIMAL', 
                'file_name' => 'total_local_tax_amount', 
                'default_value' => 1, 
                'column_name' => null,
            ],
            [
                
                'field_mapping_bid' => 1, 
                'required' => 0, 
                'field' => 'total_tax_amount', 
                'description' => null, 
                'mapping_type' => 'DECIMAL', 
                'file_name' => 'total_tax_amount', 
                'default_value' => 1, 
                'column_name' => null,
            ],
            [
                
                'field_mapping_bid' => 1, 
                'required' => 0, 
                'field' => 'total_discount_amount', 
                'description' => null, 
                'mapping_type' => 'DECIMAL', 
                'file_name' => 'total_discount_amount', 
                'default_value' => 1, 
                'column_name' => null,
            ],
            [
                
                'field_mapping_bid' => 1, 
                'required' => 0, 
                'field' => 'total_vat_exempt_amount', 
                'description' => null, 
                'mapping_type' => 'DECIMAL', 
                'file_name' => 'total_vat_exempt_amount', 
                'default_value' => 1, 
                'column_name' => null,
            ],
            [
                
                'field_mapping_bid' => 1, 
                'required' => 0, 
                'field' => 'total_vat_deduct_amount', 
                'description' => null, 
                'mapping_type' => 'DECIMAL', 
                'file_name' => 'total_vat_deduct_amount', 
                'default_value' => 1, 
                'column_name' => null,
            ],
            [
                
                'field_mapping_bid' => 1, 
                'required' => 0, 
                'field' => 'total_vatable_sales', 
                'description' => null, 
                'mapping_type' => 'DECIMAL', 
                'file_name' => 'total_vatable_sales', 
                'default_value' => 1, 
                'column_name' => null,
            ],
            [
                
                'field_mapping_bid' => 1, 
                'required' => 0, 
                'field' => 'total_zero_rated_sales', 
                'description' => null, 
                'mapping_type' => 'DECIMAL', 
                'file_name' => 'total_zero_rated_sales', 
                'default_value' => 1, 
                'column_name' => null,
            ],
            [
                
                'field_mapping_bid' => 1, 
                'required' => 0, 
                'field' => 'log_date', 
                'description' => null, 
                'mapping_type' => 'DATE', 
                'file_name' => 'log_date', 
                'default_value' => 1, 
                'column_name' => null,
            ],
            [
                
                'field_mapping_bid' => 1, 
                'required' => 0, 
                'field' => 'order_number', 
                'description' => null, 
                'mapping_type' => 'INT', 
                'file_name' => 'order_number', 
                'default_value' => 1, 
                'column_name' => null,
            ],
            [
                
                'field_mapping_bid' => 1, 
                'required' => 0, 
                'field' => 'table_number', 
                'description' => null, 
                'mapping_type' => 'VARCHAR', 
                'file_name' => 'table_number', 
                'default_value' => '""', 
                'column_name' => null,
            ],
            [
                
                'field_mapping_bid' => 1, 
                'required' => 0, 
                'field' => 'guest_count', 
                'description' => null, 
                'mapping_type' => 'INT', 
                'file_name' => 'guest_count', 
                'default_value' => 0, 
                'column_name' => null,
            ],
            [
                'field_mapping_bid' => 1,
                'required' => 0,
                'field' =>'split_number',
                'description' => null, 
                'mapping_type' => 'INT',
                'file_name' => 'split_number',
                'default_value' => 1,
                'column_name' => null,
            ],
            [
                'field_mapping_bid' => 1,
                'required' => 0,
                'field' =>'number',
                'description' => null, 
                'mapping_type' => 'INT',
                'file_name' => 'number',
                'default_value' => 1,
                'column_name' => null,
            ],
            [
                'field_mapping_bid' => 1,
                'required' => 0,
                'field' =>'total',
                'description' => null, 
                'mapping_type' => 'DECIMAL',
                'file_name' => 'total',
                'default_value' => 0,
                'column_name' => null,
            ],
            [
                'field_mapping_bid' => 1,
                'required' => 0,
                'field' =>'discount_amount',
                'description' => null, 
                'mapping_type' => 'DECIMAL',
                'file_name' => 'discount_amount',
                'default_value' => 0,
                'column_name' => null,
            ],
            [
                'field_mapping_bid' => 1,
                'required' => 0,
                'field' =>'free_items_amount',
                'description' => null, 
                'mapping_type' => 'DECIMAL',
                'file_name' => 'free_items_amount',
                'default_value' => 0,
                'column_name' => null,
            ],
            [
                'field_mapping_bid' => 1,
                'required' => 0,
                'field' =>'vat_deduct_amount',
                'description' => null, 
                'mapping_type' => 'DECIMAL',
                'file_name' => 'vat_deduct_amount',
                'default_value' => 0,
                'column_name' => null,
            ],
            [
                'field_mapping_bid' => 1,
                'required' => 0,
                'field' =>'vat_exempt_amount',
                'description' => null, 
                'mapping_type' => 'DECIMAL',
                'file_name' => 'vat_exempt_amount',
                'default_value' => 0,
                'column_name' => null,
            ],
            [
                'field_mapping_bid' => 1,
                'required' => 0,
                'field' =>'original_amount',
                'description' => null, 
                'mapping_type' => 'DECIMAL',
                'file_name' => 'original_amount',
                'default_value' => 0,
                'column_name' => null,
            ],
            [
                'field_mapping_bid' => 1,
                'required' => 0,
                'field' =>'quantity',
                'description' => null, 
                'mapping_type' => 'DECIMAL',
                'file_name' => 'quantity',
                'default_value' => 1,
                'column_name' => null,
            ],
            [
                'field_mapping_bid' => 1,
                'required' => 0,
                'field' =>'local_tax_amount',
                'description' => null, 
                'mapping_type' => 'DECIMAL',
                'file_name' => 'local_tax_amount',
                'default_value' => 0,
                'column_name' => null,
            ],
            [
                'field_mapping_bid' => 1,
                'required' => 0,
                'field' =>'tax_amount',
                'description' => null, 
                'mapping_type' => 'DECIMAL',
                'file_name' => 'tax_amount',
                'default_value' => 0,
                'column_name' => null,
            ],
            [
                'field_mapping_bid' => 1,
                'required' => 0,
                'field' =>'service_charge',
                'description' => null, 
                'mapping_type' => 'DECIMAL',
                'file_name' => 'service_charge',
                'default_value' => 0,
                'column_name' => null,
            ],
            [
                'field_mapping_bid' => 1,
                'required' => 0,
                'field' =>'vatable_sales',
                'description' => null, 
                'mapping_type' => 'DECIMAL',
                'file_name' => 'vatable_sales',
                'default_value' => 0,
                'column_name' => null,
            ],
            [
                'field_mapping_bid' => 1,
                'required' => 0,
                'field' =>'zero_rated_sales',
                'description' => null, 
                'mapping_type' => 'DECIMAL',
                'file_name' => 'zero_rated_sales',
                'default_value' => 0,
                'column_name' => null,
            ],
            [
                'field_mapping_bid' => 1,
                'required' => 0,
                'field' =>'eligible_amount_to_earn_points',
                'description' => null, 
                'mapping_type' => 'DECIMAL',
                'file_name' => 'eligible_amount_to_earn_points',
                'default_value' => 0,
                'column_name' => null,
            ],
            [
                'field_mapping_bid' => 1,
                'required' => 0,
                'field' =>'total_tender',
                'description' => null, 
                'mapping_type' => 'DECIMAL',
                'file_name' => 'total_tender',
                'default_value' => 0,
                'column_name' => null,
            ],
            [
                'field_mapping_bid' => 1,
                'required' => 0,
                'field' =>'cashier_id',
                'description' => null, 
                'mapping_type' => 'INT',
                'file_name' => 'cashier_id',
                'default_value' => 0,
                'column_name' => null,
            ],
            [
                'field_mapping_bid' => 1,
                'required' => 0,
                'field' =>'cashier_name',
                'description' => null, 
                'mapping_type' => 'VARCHAR',
                'file_name' => 'cashier_name',
                'default_value' => 0,
                'column_name' => null,
            ],
            [
                'field_mapping_bid' => 1,
                'required' => 0,
                'field' =>'customer_id',
                'description' => null, 
                'mapping_type' => 'INT',
                'file_name' => 'customer_id',
                'default_value' => 0,
                'column_name' => null,
            ],
            [
                'field_mapping_bid' => 1,
                'required' => 0,
                'field' =>'customer_type',
                'description' => null, 
                'mapping_type' => 'INT',
                'file_name' => 'customer_type',
                'default_value' => 0,
                'column_name' => null,
            ],
            [
                'field_mapping_bid' => 1,
                'required' => 0,
                'field' =>'customer_name',
                'description' => null, 
                'mapping_type' => 'VARCHAR',
                'file_name' => 'customer_name',
                'default_value' => '""',
                'column_name' => null,
            ],
            [
                'field_mapping_bid' => 1,
                'required' => 0,
                'field' =>'customer_address',
                'description' => null, 
                'mapping_type' => 'VARCHAR',
                'file_name' => 'customer_address',
                'default_value' => '""',
                'column_name' => null,
            ],
            [
                'field_mapping_bid' => 1,
                'required' => 0,
                'field' =>'payment_method_title',
                'description' => null, 
                'mapping_type' => 'VARCHAR',
                'file_name' => 'payment_method_title',
                'default_value' => 'CASH',
                'column_name' => null,
            ],
            [
                'field_mapping_bid' => 1,
                'required' => 0,
                'field' =>'payment_method_total',
                'description' => null, 
                'mapping_type' => 'DECIMAL',
                'file_name' => 'payment_method_total',
                'default_value' => 0,
                'column_name' => null,
            ],
            [
                'field_mapping_bid' => 1,
                'required' => 0,
                'field' =>'payment_method_account_number',
                'description' => null, 
                'mapping_type' => 'VARCHAR',
                'file_name' => 'payment_method_account_number',
                'default_value' => '""',
                'column_name' => null,
            ],
            [
                'field_mapping_bid' => 1,
                'required' => 0,
                'field' => 'product_id',
                'description' => null, 
                'mapping_type' => 'INT',
                'file_name' => 'id',
                'default_value' => '""',
                'column_name' => null,
            ],
            [
                'field_mapping_bid' => 1,
                'required' => 0,
                'field' => 'product_menu_code',
                'description' => null, 
                'mapping_type' => 'BIGINT',
                'file_name' => 'menu_code',
                'default_value' => '""',
                'column_name' => null,
            ],
            [
                'field_mapping_bid' => 1,
                'required' => 0,
                'field' => 'product_name',
                'description' => null, 
                'mapping_type' => 'VARCHAR',
                'file_name' => 'name',
                'default_value' => '""',
                'column_name' => null,
            ],
            [
                'field_mapping_bid' => 1,
                'required' => 0,
                'field' => 'product_description',
                'description' => null, 
                'mapping_type' => 'VARCHAR',
                'file_name' => 'description',
                'default_value' => '""',
                'column_name' => null,
            ],
            [
                'field_mapping_bid' => 1,
                'required' => 0,
                'field' => 'product_long_description',
                'description' => null, 
                'mapping_type' => 'VARCHAR',
                'file_name' => 'long_description',
                'default_value' => '""',
                'column_name' => null,
            ],
            [
                'field_mapping_bid' => 1,
                'required' => 0,
                'field' => 'product_quantity',
                'description' => null, 
                'mapping_type' => 'DECIMAL',
                'file_name' => 'quantity',
                'default_value' => '""',
                'column_name' => null,
            ],
            [
                'field_mapping_bid' => 1,
                'required' => 0,
                'field' => 'product_tax_percentage',
                'description' => null, 
                'mapping_type' => 'DECIMAL',
                'file_name' => 'tax_percentage',
                'default_value' => 12.0,
                'column_name' => null,
            ],
            [
                'field_mapping_bid' => 1,
                'required' => 0,
                'field' => 'product_is_free',
                'description' => null, 
                'mapping_type' => 'INT',
                'file_name' => 'is_free',
                'default_value' => 0,
                'column_name' => null,
            ],
            [
                'field_mapping_bid' => 1,
                'required' => 0,
                'field' => 'product_is_vatable',
                'description' => null, 
                'mapping_type' => 'INT',
                'file_name' => 'is_vatable',
                'default_value' => 1,
                'column_name' => null,
            ],
            [
                'field_mapping_bid' => 1,
                'required' => 0,
                'field' => 'product_original_price',
                'description' => null, 
                'mapping_type' => 'DECIMAL',
                'file_name' => 'original_price',
                'default_value' => 0,
                'column_name' => null,
            ],
            [
                'field_mapping_bid' => 1,
                'required' => 0,
                'field' => 'product_price',
                'description' => null, 
                'mapping_type' => 'DECIMAL',
                'file_name' => 'price',
                'default_value' => 0,
                'column_name' => null,
            ],
            [
                'field_mapping_bid' => 1,
                'required' => 0,
                'field' => 'product_total_addon',
                'description' => null, 
                'mapping_type' => 'DECIMAL',
                'file_name' => 'total_addon',
                'default_value' => 0,
                'column_name' => null,
            ],
            [
                'field_mapping_bid' => 1,
                'required' => 0,
                'field' => 'product_total_amount',
                'description' => null, 
                'mapping_type' => 'DECIMAL',
                'file_name' => 'product_total_amount',
                'default_value' => 0,
                'column_name' => null,
            ],
            [
                'field_mapping_bid' => 1,
                'required' => 0,
                'field' => 'product_amount_discount',
                'description' => null, 
                'mapping_type' => 'DECIMAL',
                'file_name' => 'amount_discount',
                'default_value' => 0,
                'column_name' => null,
            ],
            [
                'field_mapping_bid' => 1,
                'required' => 0,
                'field' => 'product_vatable_sales',
                'description' => null, 
                'mapping_type' => 'DECIMAL',
                'file_name' => 'vatable_sales',
                'default_value' => 0,
                'column_name' => null,
            ],
            [
                'field_mapping_bid' => 1,
                'required' => 0,
                'field' => 'product_zero_rated_sales',
                'description' => null, 
                'mapping_type' => 'DECIMAL',
                'file_name' => 'zero_rated_sales',
                'default_value' => 0,
                'column_name' => null,
            ],
            [
                'field_mapping_bid' => 1,
                'required' => 0,
                'field' => 'product_tax',
                'description' => null, 
                'mapping_type' => 'DECIMAL',
                'file_name' => 'tax',
                'default_value' => 0,
                'column_name' => null,
            ],
            [
                'field_mapping_bid' => 1,
                'required' => 0,
                'field' => 'product_vat_exempt',
                'description' => null, 
                'mapping_type' => 'DECIMAL',
                'file_name' => 'vat_exempt',
                'default_value' => 0,
                'column_name' => null,
            ],
            [
                'field_mapping_bid' => 1,
                'required' => 0,
                'field' => 'product_vat_deduct',
                'description' => null, 
                'mapping_type' => 'DECIMAL',
                'file_name' => 'vat_deduct',
                'default_value' => 0,
                'column_name' => null,
            ],
            [
                'field_mapping_bid' => 1,
                'required' => 0,
                'field' => 'product_split_number',
                'description' => null, 
                'mapping_type' => 'INT',
                'file_name' => 'split_number',
                'default_value' => 0,
                'column_name' => null,
            ],
            [
                'field_mapping_bid' => 1,
                'required' => 0,
                'field' => 'order_type_id',
                'description' => null, 
                'mapping_type' => 'INT',
                'file_name' => 'id',
                'default_value' => 0,
                'column_name' => null,
            ],
            [
                'field_mapping_bid' => 1,
                'required' => 0,
                'field' => 'order_type_name',
                'description' => null, 
                'mapping_type' => 'VARCHAR',
                'file_name' => 'name',
                'default_value' => '""',
                'column_name' => null,
            ],
            [
                'field_mapping_bid' => 1,
                'required' => 0,
                'field' => 'category_id',
                'description' => null, 
                'mapping_type' => 'INT',
                'file_name' => 'id',
                'default_value' => 0,
                'column_name' => null,
            ],
            [
                'field_mapping_bid' => 1,
                'required' => 0,
                'field' => 'category_name',
                'description' => null, 
                'mapping_type' => 'VARCHAR',
                'file_name' => 'name',
                'default_value' => '""',
                'column_name' => null,
            ],
            
            [
                'field_mapping_bid' => 1,
                'required' => 0,
                'field' => 'transaction_product_bid',
                'description' => null, 
                'mapping_type' => 'VARCHAR',
                'file_name' => 'AD',
                'default_value' => '1',
                'column_name' => 'transaction_product_bid',
            ],
            [
                'field_mapping_bid' => 1,
                'required' => 0,
                'field' => 'addon_id',
                'description' => null, 
                'mapping_type' => 'VARCHAR',
                'file_name' => 'AD',
                'default_value' => 1,
                'column_name' => 'id',
            ],
            [
                'field_mapping_bid' => 1,
                'required' => 0,
                'field' => 'parent_product_bid',
                'description' => null, 
                'mapping_type' => 'VARCHAR',
                'file_name' => 'AD',
                'default_value' => '1',
                'column_name' => 'parent_product_bid',
            ],
            [
                'field_mapping_bid' => 1,
                'required' => 0,
                'field' => 'product_uom_packaging_bid',
                'description' => null, 
                'mapping_type' => 'VARCHAR',
                'file_name' => 'AD',
                'default_value' => '1',
                'column_name' => 'product_uom_packaging_bid',
            ],
            [
                'field_mapping_bid' => 1,
                'required' => 0,
                'field' => 'addon_name',
                'description' => null, 
                'mapping_type' => 'VARCHAR',
                'file_name' => 'name',
                'default_value' => '""',
                'column_name' => null,
            ],
            [
                'field_mapping_bid' => 1,
                'required' => 0,
                'field' => 'addon_quantity',
                'description' => null, 
                'mapping_type' => 'DECIMAL',
                'file_name' => 'quantity',
                'default_value' => 0,
                'column_name' => null,
            ],
            [
                'field_mapping_bid' => 1,
                'required' => 0,
                'field' => 'addon_original_price',
                'description' => null, 
                'mapping_type' => 'DECIMAL',
                'file_name' => 'original_price',
                'default_value' => 0,
                'column_name' => null,
            ],
            [
                'field_mapping_bid' => 1,
                'required' => 0,
                'field' => 'addon_price',
                'description' => null, 
                'mapping_type' => 'DECIMAL',
                'file_name' => 'price',
                'default_value' => 0,
                'column_name' => null,
            ],
            [
                'field_mapping_bid' => 1,
                'required' => 0,
                'field' => 'addon_total_amount',
                'description' => null, 
                'mapping_type' => 'DECIMAL',
                'file_name' => 'total_amount',
                'default_value' => 0,
                'column_name' => null,
            ],
            [
                'field_mapping_bid' => 1,
                'required' => 0,
                'field' => 'discount_id',
                'description' => null, 
                'mapping_type' => 'INT',
                'file_name' => 'id',
                'default_value' => 0,
                'column_name' => 'id',
            ],
            [
                'field_mapping_bid' => 1,
                'required' => 0,
                'field' => 'transaction_product_bid',
                'description' => null, 
                'mapping_type' => 'INT',
                'file_name' => 'PD',
                'default_value' => 1,
                'column_name' => 'transaction_product_bid',
            ],
            [
                'field_mapping_bid' => 1,
                'required' => 0,
                'field' => 'discount_mandated',
                'description' => null, 
                'mapping_type' => 'INT',
                'file_name' => 'mandated',
                'default_value' => 0,
                'column_name' => null,
            ],
            [
                'field_mapping_bid' => 1,
                'required' => 0,
                'field' => 'discount_title',
                'description' => null, 
                'mapping_type' => 'VARCHAR',
                'file_name' => 'title',
                'default_value' => '""',
                'column_name' => null,
            ],
            [
                'field_mapping_bid' => 1,
                'required' => 0,
                'field' => 'discount_total',
                'description' => null, 
                'mapping_type' => 'DECIMAL',
                'file_name' => 'total',
                'default_value' => 0,
                'column_name' => null,
            ],
            [
                'field_mapping_bid' => 1,
                'required' => 0,
                'field' => 'discount_amount_discount',
                'description' => null, 
                'mapping_type' => 'DECIMAL',
                'file_name' => 'amount_discount',
                'default_value' => 0,
                'column_name' => null,
            ],
            [
                'field_mapping_bid' => 1,
                'required' => 0,
                'field' => 'discount_vat_deduct',
                'description' => null, 
                'mapping_type' => 'DECIMAL',
                'file_name' => 'vat_deduct',
                'default_value' => 0,
                'column_name' => null,
            ],
            [
                'field_mapping_bid' => 1,
                'required' => 0,
                'field' => 'discount_vat_exempt',
                'description' => null, 
                'mapping_type' => 'DECIMAL',
                'file_name' => 'vat_exempt',
                'default_value' => 0,
                'column_name' => null,
            ],
            [
                'field_mapping_bid' => 1,
                'required' => 0,
                'field' => 'price_override_details_price',
                'description' => null, 
                'mapping_type' => 'DECIMAL',
                'file_name' => 'price',
                'default_value' => '""',
                'column_name' => null,
            ],
            [
                'field_mapping_bid' => 1,
                'required' => 0,
                'field' => 'price_override_details_approved_by',
                'description' => null, 
                'mapping_type' => 'VARCHAR',
                'file_name' => 'approved_by',
                'default_value' => '""',
                'column_name' => null,
            ],
            [
                'field_mapping_bid' => 1,
                'required' => 0,
                'field' => 'price_override_details_approved_date',
                'description' => null, 
                'mapping_type' => 'DATETIME',
                'file_name' => 'approved_date',
                'default_value' => '""',
                'column_name' => null,
            ],
            
            

        ];

        foreach ($field_mapping_details as $value) {
            FieldMappingDetail::create($value);
        }
    }

    /**
     * Reverts the database seeder.
     */
    public function down(): void
    {
        // Remove your data
    }
}
